* status   
#MyUniqueID2016-10-02_13-36-15-3938  
* Purpose of this file: experiment with how org reacts to various things
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* helpful menu item in emacs org mode: Org:Hyperlinks:Literal Links   
** emacs/org goofs this up when you have multiple frames (C-x-5-2)   
*** have to toggle it a few times trying to make it refresh and show current data
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* separate these into internal links vs external links?   
* http://orgmode.org/manual/External-links.html#External-links <<org external links>>   
* http://orgmode.org/manual/Internal-links.html#Internal-links  <<org internal links>>   
** tried out radio targets in    [[file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160920TestRadioTargets.org][20160920TestRadioTargets.org]]      
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* links of interest to org files
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets file:OrgModeFileCrawlerMain.org::python works
* brackets [[file:OrgModeFileCrawlerMain.org::python]] works
* no brackets file+sys:OrgModeFileCrawlerMain.org::python opens new empty file in emacs
* brackets [[file+sys:OrgModeFileCrawlerMain.org::python]] opens new empty file in emacs
* no brackets file+emacs:OrgModeFileCrawlerMain.org::python opens new empty file in emacs
* brackets [[file+emacs:OrgModeFileCrawlerMain.org::python]] opens new empty file in emacs
* no brackets docview:OrgModeFileCrawlerMain.org::python following link: nothing happens
* brackets [[docview:OrgModeFileCrawlerMain.org::python]] following link: nothing happens
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets /anyFilename.org::anything 
* brackets [[/junkIt.org::anything]] works;  opens file in emacs; will find anything in headline as long as it's the entire headline
** doesn't have to be first level headline (one asterisk)
** will find first matching headline in file
* no brackets ./OrgModeFileCrawlerMain.org::python
* brackets [[./OrgModeFileCrawlerMain.org::python]] works
* no brackets ~/OrgModeFileCrawlerMain.org::python
* brackets [[~/junkIt.org::python]] works
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets OrgModeFileCrawlerMain.org::python
* brackets [[OrgModeFileCrawlerMain.org::python]] org sees this as internal link
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets file:OrgModeFileCrawlerMain.org works
* brackets [[file:OrgModeFileCrawlerMain.org]] works
* no brackets file+sys:OrgModeFileCrawlerMain.org nothing happens
* brackets [[file+sys:OrgModeFileCrawlerMain.org]] nothing happens
* no brackets file+emacs:OrgModeFileCrawlerMain.org works
* brackets [[file+emacs:OrgModeFileCrawlerMain.org]] works
* no brackets docview:OrgModeFileCrawlerMain.org nothing happens
* brackets [[docview:OrgModeFileCrawlerMain.org]] nothing happens
** no program named docview in linux (which docview); no docview in .emacs file
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets OrgModeFileCrawlerMain.org
* brackets [[OrgModeFileCrawlerMain.org]] org sees this as internal link
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets /anyFilename.org 
* brackets [[/junkIt.org]] 
* no brackets ./OrgModeFileCrawlerMain.org
* brackets [[./OrgModeFileCrawlerMain.org]] works
* no brackets ~/OrgModeFileCrawlerMain.org
* brackets [[~/junkIt.org]] works
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* links of interest to non org files
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets file:README.md::WARNING works; case insensitive search
* brackets [[file:README.md::WARNING]] works; case insensitive search
* no brackets file+sys:README.md::WARNING opens new blank file in emacs
* brackets [[file+sys:README.md::WARNING]] opens new blank file in emacs
* no brackets file+emacs:README.md::WARNING opens new blank file in emacs
* brackets [[file+emacs:README.md::WARNING]] opens new blank file in emacs
* no brackets docview:README.md::WARNING nothing happens
* brackets [[docview:README.md::WARNING]] nothing happens
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets /junkIt.txt::anything 
* brackets [[/junkIt.txt::anything]] 
* no brackets ./README.md::WARNING
* brackets [[./README.md::WARNING]]
* no brackets ~/junkIt.txt::anything
* brackets [[~/junkIt.txt::anything]] works
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets README.md::WARNING
* brackets [[README.md::WARNING]] org sees this as internal link
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets file:README.md works 
* brackets [[file:README.md]] 
* no brackets file+sys:README.md opens in emacs 
* brackets [[file+sys:README.md]] 
* no brackets file+emacs:README.md opens in emacs
* brackets [[file+emacs:README.md]] 
* no brackets docview:README.md 
* brackets [[docview:README.md]] 
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets README.md
* brackets [[README.md]] org sees this as internal link
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* no brackets /filename.txt 
* brackets [[/junkIt.txt]] works
* no brackets ./README.md
* brackets [[./README.md]] works
* no brackets ~/junkIt.txt
* brackets [[~/junkIt.txt]] works
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* file:
* [[file:]] internal link
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
*    [[nothing to find]]      
*** behaves like    [[org internal links]]      
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* if I create a link via ctrl-u-c-l, I end up with    [[file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py][20160908ExceptionTest.py]]      
** [2016-09-20 Tue] I have always done it that way, so my past assumption of file: being in a link to a file has looked right   
   
* type the name of a file in current working directory; does it automatically turn into a link?   
** 20160908ExceptionTest.py   
*** looks like no   
** /home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
*** still looks like no   
** /home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
*** still looks like no   
** file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
*** OK, if I first type file: and then paste in the rest, org mode automatically turns it into a link, with no brackets   
** file:/made/up/filename.junk   
*** typing this: org mode turned it into a clickable link automatically; no brackets   
** what if you paste it instead of type it?   
*** /home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
**** still looks like no   
* if I put square brackets, what happens to those?   
**    [[20160908ExceptionTest.py]]      
*** behaves like    [[org internal links]]      
**    [[/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py][20160908ExceptionTest.py]]      
*** behaves like    [[org external links]]      
**    [[/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py][20160908ExceptionTest.py]]      
*** behaves like    [[org external links]]      
**    [[PythonScriptOldVersions/20160526]]      
*** behaves like    [[org internal links]]      
*** kind of a surprise   
**** this is a valid relative path filename in current working directory   
**** created it via C-u-c-l and then deleted the file: and whatever else   
   
** what about    [[/made/up/filename.junk][filename.junk]]      
*** behaves like    [[org external links]]      
*** org offers to make these folders; should lack OS permission to do it in this case   
** what about    [[/home/dad84/Documents/madeupname.junk][madeupname.junk]]        
*** behaves like    [[org external links]]      
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* if you paste a hyperlink from google chrome (link to a webpage) into org mode, it becomes a clickable link   
** with no brackets   
*** can verify this via Org menu then Hyperlinks then literal links   
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
*    [[file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/OrgModeFileCrawlerMain.org::*sqlite3%20terminal%20programming%20notes][OrgModeFileCrawlerMain.org]]      
** can't seem to get this one to work; it will open file but fail to find desired heading   
** space or no space after asterisk: doesn't seem to matter   
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
*    [[file+sys:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160807PuzzleOverProgramLogic.xoj][20160807PuzzleOverProgramLogic.xoj]]      
** open via OS, like double-click   
** [2016-09-21 Wed] just gives me binary data in a buffer; clearly does not work unless my OS doesn't know how to open this file?   
** would be hard to find a file on disk with a type that emacs does not know how to open; how would you know if emacs didn't open it normally?   
** double-clicked on a file in nautilus and a new instance of emacs came up which was unresponsive and could very slowly be shut down   
* file+sys:/    need more than root of filesystem to get a link without brackets   
*    [[file+emacs:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160807PuzzleOverProgramLogic.xoj][20160807PuzzleOverProgramLogic.xoj]]      
** force open via emacs   
** get binary data in a buffer, which I guess is correct result?   
*** I thought my .emacs was set up so that .xoj files opened in xournal?   
* docview:/home/dad84/Documents/Computer/Software/PythonNotes/PythonForInformaticsSeverance/PythonForInformaticsSeverance009d2.pdf::32   
** evince opened the right document but on page 69, not 32   
*    [[id:B7423F4D]]      
** needs brackets to become a link   
** why is this in list of external links?  is it searching all my org files?  seems doubtful   
* doi:10.100/182  does not need brackets   
*    [[shell:ls *.org]]      
** end up with results in minibuffer and in another new file   
* /myself@some.where:papers/last.pdf  needs brackets   
* #my-custom-id     
*    [[20160908ExceptionTest.py::23  ]]      
* OrgModeFileCrawlerMain.org::what about   
* news:comp.emacs   
* elist:org-agenda   
* elisp:(find-file-other-frame "Elisp.org")   
* vm:folder   
* vm:folder#id   
* vm://myself@somewhere.org/folder#id   
* vm-imap:account:folder   
* vm-imap:account:folder#id   
* wl:folder   
* wl:folder#id   
* /home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
* ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((   
* what is and is not a link to a file according to org mode?   
*    [[/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/fsljiwen sdfsdf][fsljiwen sdfsdf]]      
** [2016-09-23 Fri] org thinks this is a file on disk   
*    [[/home/dad84/sdlfkwf fwun ofi][sdlfkwf fwun ofi]]      
** [2016-09-23 Fri] org thinks this is a file on disk   
*    [[/sdfj sdfjk sdffweh8874y9][sdfj sdfjk sdffweh8874y9]]      
** [2016-09-23 Fri] org thinks this is a file on disk   
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908Exception Test.py   
*    [[file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908Exception Test.py][20160908Exception Test.py]]      
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/20160908ExceptionTest.py   
*    [[20160908ExceptionTest.py]]     org treats this as internal link   
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/PythonScriptOldVersions     
*    [[./]]    this goes to dired   
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler   
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler   
** weird how org does not make this clickable even though it begins with file:   
** if your script repaired this broken link, it would become clickable in org mode, even without brackets   
* file:/home/dad84/Documents/Computer/Software/OrgModeNotes/MyOrgModeScripts/OrgModeFileCrawler/a   
** if your script repaired this broken link, it would become clickable in org mode, even without brackets   
*    [[file:a][a]]      
*    [[/]]      
* file:/   
** it's weird how this is a valid link to root of filesystem (works when in brackets)   
* /home/dad84/20160908ExceptionTest.py     
